server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /blog/ {
        root /usr/share/nginx/html;
        index index.html;
    }

    # Nginx stub_status for Prometheus monitoring
    location /metrics {
        stub_status on;
        access_log off;
        allow all;
    }
}
